server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Regra que resolve o 404 em rotas do React:
        try_files $uri $uri/ /index.html;
    }
}